### ISSUE TITLE
Avoid duplication b/w standards/README.md and docs/standards/certification/overview.md

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/docs#166]
We currently have the list of standards-tested (and health-monitored) SCS clouds in the standards repo README.md and in the docs repo standards/certification/overview.md (https://docs.scs.community/standards/certification/overview).
Duplication is bad: Information needs to be managed at two places and is prone to diverge.

Options:
(1) Put a link to https://docs.scs.community/standards/certification/overview into the the standards/README.md file
(2) Build the list on the docs page from information in the standards repo

(1) is easier to do, but has the risk that changes to the certification actions may need to touch two repos which may more easily overlooked by contributors.

**Comment by mbuechse** [comment]
I think some version of (2) is not too hard to do. It becomes harder the more robust you want it to be. What we could do, for instance:

- use comments such as `<!-- begin compliance table -->` and `<!-- end compliance table -->` to demarcate what is to be copied (provided that the markdown check will let us use these comments)
- read what's between these comments and put it [into the relevant file in the docs page](https://github.com/SovereignCloudStack/docs/blob/main/standards/certification/overview.md) -- maybe also use some special comment as a placeholde there

**Comment by mbuechse** [comment]
@maxwolfs Would you mind if I did this? If you're indeed okay with it, maybe just unassign yourself (you are still subscribed, and you can always reassign yourself).

**Comment by maxwolfs** [comment]
@mbuechse Yeah sure go for it, Thanks! :) 

Some time ago (before the standards rework) we already had a working version of what was mentioned with (2). So I think this should be the way to do it again. But one step back: I think the _main_  information point for people looking for certified cloud should be on a specific place on our page, currently [here] (https://docs.scs.community/standards/certification/overview) and not on [github](https://github.com/SovereignCloudStack/standards). This way we can make sure there is more context, especially for non github users. It was originally published there because the first tests were implemented with github actions . Imo GitHub represents more like the work bench, but not the best place to publish the information. What's actually the current perspective on zuul?

**Comment by mbuechse** [comment]
@maxwolfs I think we will generate this table automatically once https://github.com/SovereignCloudStack/standards/issues/381 comes to fruition. Then we may no longer need to touch any repository (at least not manually), and the whole duplication goes away. Maybe we just wait? I don't know how many more changes to the table we expect in the near future.

**Comment by mbuechse** [comment]
Just an update: this will be dealt with in the course of https://github.com/SovereignCloudStack/standards/issues/672.
